# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KraftkitStaging < Formula
  desc "Build and use highly customized and ultra-lightweight unikernels."
  homepage "https://kraftkit.sh"
  version "0.12.16-13-g22e305d1"
  license "BSD-3-Clause"

  depends_on "aarch64-elf-binutils"
  depends_on "aarch64-elf-gcc"
  depends_on "coreutils"
  depends_on "gawk"
  depends_on "gnu-sed"
  depends_on "grep"
  depends_on "m4"
  depends_on "make"
  depends_on "qemu"
  depends_on "socat"
  depends_on "wget"
  depends_on "x86_64-elf-binutils"
  depends_on "x86_64-elf-gcc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-13-g22e305d1/kraft_0.12.16-13-g22e305d1_darwin_amd64.tar.gz"
      sha256 "63b7f0834bf5b89dbd90eb370813f994c84cf7666f25681707e614b3cdec2ada"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-13-g22e305d1/kraft_0.12.16-13-g22e305d1_darwin_arm64.tar.gz"
      sha256 "d42850a20c817694f382d6b40e52811bf57208614e3d5418001f56a0ea152e55"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-13-g22e305d1/kraft_0.12.16-13-g22e305d1_linux_amd64.tar.gz"
        sha256 "d9b1829a2aa5e78717f67d2f6b0dcae0732abdb580a7cd4681705beaf9c47a6f"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-13-g22e305d1/kraft_0.12.16-13-g22e305d1_linux_arm64.tar.gz"
        sha256 "c507eb8ed72042eb35ec390ec3d33e42cf167ad18629ecac2e11b30d769f583f"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
  end
end
