# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KraftkitStaging < Formula
  desc "Build and use highly customized and ultra-lightweight unikernels."
  homepage "https://kraftkit.sh"
  version "0.12.16-9-g99ec1c74"
  license "BSD-3-Clause"

  depends_on "aarch64-elf-binutils"
  depends_on "aarch64-elf-gcc"
  depends_on "coreutils"
  depends_on "gawk"
  depends_on "gnu-sed"
  depends_on "grep"
  depends_on "m4"
  depends_on "make"
  depends_on "qemu"
  depends_on "socat"
  depends_on "wget"
  depends_on "x86_64-elf-binutils"
  depends_on "x86_64-elf-gcc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-9-g99ec1c74/kraft_0.12.16-9-g99ec1c74_darwin_amd64.tar.gz"
      sha256 "2b61c8c5cfde91a9a1ee34ece69e049da1f7496c04f9bab6e826506a2fa33b59"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-9-g99ec1c74/kraft_0.12.16-9-g99ec1c74_darwin_arm64.tar.gz"
      sha256 "17a9a5331773b33f7d6d64138aa39bd374c6110e52badaaa5435c316f1dee6fb"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-9-g99ec1c74/kraft_0.12.16-9-g99ec1c74_linux_amd64.tar.gz"
        sha256 "025f6d59712626f844f210feaafe03bd24a28d7f36bee3ad307bebd96ea46aeb"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-9-g99ec1c74/kraft_0.12.16-9-g99ec1c74_linux_arm64.tar.gz"
        sha256 "cfca0e2e22e9f39f44e3f323c039767bf46d36a52586d37a24269d571aab2a3c"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
  end
end
