# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KraftkitStaging < Formula
  desc "Build and use highly customized and ultra-lightweight unikernels."
  homepage "https://kraftkit.sh"
  version "0.12.16-11-g2f8635f7"
  license "BSD-3-Clause"

  depends_on "aarch64-elf-binutils"
  depends_on "aarch64-elf-gcc"
  depends_on "coreutils"
  depends_on "gawk"
  depends_on "gnu-sed"
  depends_on "grep"
  depends_on "m4"
  depends_on "make"
  depends_on "qemu"
  depends_on "socat"
  depends_on "wget"
  depends_on "x86_64-elf-binutils"
  depends_on "x86_64-elf-gcc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-11-g2f8635f7/kraft_0.12.16-11-g2f8635f7_darwin_amd64.tar.gz"
      sha256 "321035dac3e4d527bb1b0d8d82b852337dcc35e986e3ba3074fbb303f7f0714b"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-11-g2f8635f7/kraft_0.12.16-11-g2f8635f7_darwin_arm64.tar.gz"
      sha256 "dfccf7bf7f0e248efe3bab63bf3a30c2e35d1079e8fb4b931b6efbab3f670b21"

      def install
        bin.install "kraft"
        man1.install Dir["man/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-11-g2f8635f7/kraft_0.12.16-11-g2f8635f7_linux_amd64.tar.gz"
        sha256 "c204ab05fe297bc1f736191794082f96d40c3d10533db5114d8f827e4825b5d1"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/unikraft/kraftkit/releases/download/v0.12.16-11-g2f8635f7/kraft_0.12.16-11-g2f8635f7_linux_arm64.tar.gz"
        sha256 "4a15e63b2f5d8508385b07073b287b710f2ba514539db072f8431b4f8eafe644"

        def install
          bin.install "kraft"
          man1.install Dir["man/*"]
        end
      end
    end
  end
end
