# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnikraftStaging < Formula
  desc "The official CLI for Unikraft Cloud — deploy and manage unikernels globally in milliseconds."
  homepage "https://unikraft.com"
  version "0.5.2-staging.16"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.5.2-staging.16/unikraft-cli_0.5.2-staging.16_darwin_amd64.tar.gz"
      sha256 "2dddfadc2c2e75490aceb4231eed902d7b343150edde0ecd4a872943ff2bd66e"

      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.5.2-staging.16/unikraft-cli_0.5.2-staging.16_darwin_arm64.tar.gz"
      sha256 "0c8d1c8f268f17ff99d7ca7b7fe14dca6f53c88360558ede232ec9ba7968bbbc"

      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.5.2-staging.16/unikraft-cli_0.5.2-staging.16_linux_amd64.tar.gz"
      sha256 "ecf45a9a0a757780dd17ac9105775909585a3d95547b4143d18768760d50aa48"
      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.5.2-staging.16/unikraft-cli_0.5.2-staging.16_linux_arm64.tar.gz"
      sha256 "2925977f3e3922ffe0091c34308fb1d823c6211bf4acb2e60c6ec7f5b9d2f830"
      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
  end
end
