# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnikraftStaging < Formula
  desc "The official CLI for Unikraft Cloud — deploy and manage unikernels globally in milliseconds."
  homepage "https://unikraft.com"
  version "0.5.2-staging.10"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.5.2-staging.10/unikraft-cli_0.5.2-staging.10_darwin_amd64.tar.gz"
      sha256 "f093f38295a3a90e4973c372e0b0961a7ce5dde6ceba96771c9d24e30339c01b"

      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.5.2-staging.10/unikraft-cli_0.5.2-staging.10_darwin_arm64.tar.gz"
      sha256 "b8c68a5a6a0b66ffc05f7597f4252c8ceb153004a393f9fedeacce6ed1343e33"

      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.5.2-staging.10/unikraft-cli_0.5.2-staging.10_linux_amd64.tar.gz"
      sha256 "54c4165c65d6fdab2a00cf73aa23c1f3038a0291fbd1c1c8b75707fe983bef07"
      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unikraft-cloud/cli/releases/download/v0.5.2-staging.10/unikraft-cli_0.5.2-staging.10_linux_arm64.tar.gz"
      sha256 "5e2a5328c4a8e9a14a2b9b2e63fa323195d7eed25258567cd23361dce6513ae0"
      define_method(:install) do
        bin.install "unikraft"
        man1.install Dir["docs/man/*.1.gz"]
      end
    end
  end
end
